#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


working_dir="$(dirname "${0}")"
source "${working_dir}/constants.sh"


if [[ "${PG_USER_NAME}" == "postgres" ]]; then
    echo "Backing up as 'postgres' user is not supported. Assign 'POSTGRES_USER' env with another one and try again."
    exit 1
fi

export PGHOST="${PG_INTERNAL_HOST}"
export PGPORT="${PG_INTERNAL_PORT}"
export PGUSER="${PG_USER_NAME}"
export PGPASSWORD="${PG_USER_PASSWORD}"

backup_filename="${BACKUP_FILE_PREFIX}_$(TZ=${TZ} date +'%Y_%m_%dT%H_%M_%S').sql.gz"
backup_date="$(TZ=${TZ} date +'%Y_%m_%dT%H_%M_%S')"

echo "${backup_date} - Backing up the '${PG_DATABASE_NAME}' database..."
pg_dump -F c "${PG_DATABASE_NAME}" -f "${BACKUP_DIR_PATH}/${backup_filename}"
echo "'${PG_DATABASE_NAME}' database backup '${backup_filename}' has been created and placed in '${BACKUP_DIR_PATH}'."
