"""create users table

Revision ID: 75aa11e7b302
Revises: 
Create Date: 2025-06-24 22:43:32.804844

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "75aa11e7b302"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("hashed_password", sa.String(), nullable=True),
    sa.Column("oauth_provider", sa.String(), nullable=True),
    sa.Column("oauth_id", sa.String(), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
