"""Revision ID: 9fc42eab1680
Revises: 52f61cddb4a2
Create Date: 2025-07-22 17:41:06.303545

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fc42eab1680"
down_revision: str | Sequence[str] | None = "52f61cddb4a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "full_name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "full_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
