"""

Revision ID: b2343acbfbeb
Revises: 9fc42eab1680
Create Date: 2025-09-01 15:15:19.357827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2343acbfbeb'
down_revision: Union[str, Sequence[str], None] = '9fc42eab1680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejection_reason',
    sa.Column('reason_text', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('status', sa.String(), server_default='pending', nullable=False))
    op.add_column('projects', sa.Column('approved_by_admin_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('rejection_reason_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'rejection_reason', ['rejection_reason_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['approved_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'rejection_reason_id')
    op.drop_column('projects', 'approved_at')
    op.drop_column('projects', 'approved_by_admin_id')
    op.drop_column('projects', 'status')
    op.drop_table('user_roles')
    op.drop_table('roles')
    op.drop_table('rejection_reason')
    # ### end Alembic commands ###
